preprocess:
  input_dir: "data/raw/data.csv"
  output_dir: "data/processed/preprocessed_data.csv"

train:
  data_dir: "data/processed/preprocessed_data.csv"
  model_dir: "models/model.pkl"
  random_state: 42
  n_estimators: 100
  max_depth: 5